# Generated by Django 2.0.4 on 2018-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompID', models.IntegerField(default=1)),
                ('OperatorName', models.CharField(default='Admin', max_length=60)),
                ('location', models.CharField(blank=True, max_length=800)),
                ('ImageUrl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='CountryID',
            field=models.IntegerField(default=0),
        ),
    ]
