# Generated by Django 2.0.4 on 2018-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50)),
                ('AirPort', models.CharField(max_length=50)),
                ('FlightDate', models.DateField()),
                ('NoOfSeats', models.IntegerField()),
                ('HotelName', models.CharField(max_length=50)),
                ('ADTPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CHDPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InfPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SingleDiff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Days', models.IntegerField()),
                ('FlightName', models.CharField(max_length=150)),
            ],
        ),
    ]
