# Generated by Django 2.0.4 on 2018-05-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_hotelurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='HotelUrl',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
