# Generated by Django 2.0.4 on 2018-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groupprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprogram',
            name='titleProgtxt',
            field=models.CharField(default='اليوم الاول', max_length=50),
        ),
    ]
